# Generated by Django 4.0.4 on 2022-05-31 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('restaurant_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='restaurant',
            name='score',
            field=models.FloatField(default='0'),
        ),
    ]
